version: "3.9"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file: ./api-gateway/.env
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379

  identity-service:
    build: ./identity-service
    env_file: ./identity-service/.env
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379

  product-service:
    build: ./product-service
    env_file: ./product-service/.env
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379

  media-service:
    build: ./media-service
    env_file: ./media-service/.env
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379

  search-service:
    build: ./search-service
    env_file: ./search-service/.env
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379

  cart-service:
    build: ./cart-service
    env_file: ./cart-service/.env
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
