FROM node:20-alpine

WORKDIR /usr/src/app

# Install pnpm
RUN npm install -g pnpm@10.15.0

# Copy package.json & lockfile
COPY package*.json pnpm-lock.yaml ./

# Install deps (Skip dev pruning so nodemon + tsc work)
RUN pnpm install

# Copy source code
COPY . .

# Expose the port
EXPOSE 3002

# Run in dev mode (ts-node-dev or nodemon + tsc -w)
CMD ["pnpm", "run", "dev"]